set(_CATKIN_CURRENT_PACKAGE "afrl_radar")
set(afrl_radar_VERSION "0.0.0")
set(afrl_radar_MAINTAINER "capstone2020 <capstone2020@todo.todo>")
set(afrl_radar_PACKAGE_FORMAT "2")
set(afrl_radar_BUILD_DEPENDS "roscpp" "sensor_msgs")
set(afrl_radar_BUILD_EXPORT_DEPENDS "roscpp" "sensor_msgs")
set(afrl_radar_BUILDTOOL_DEPENDS "catkin")
set(afrl_radar_BUILDTOOL_EXPORT_DEPENDS )
set(afrl_radar_EXEC_DEPENDS "roscpp" "sensor_msgs")
set(afrl_radar_RUN_DEPENDS "roscpp" "sensor_msgs")
set(afrl_radar_TEST_DEPENDS )
set(afrl_radar_DOC_DEPENDS )
set(afrl_radar_URL_WEBSITE "")
set(afrl_radar_URL_BUGTRACKER "")
set(afrl_radar_URL_REPOSITORY "")
set(afrl_radar_DEPRECATED "")